### PR TITLE
Allow min and max to have same value

### PR DESCRIPTION
**Pull request by jhblacklock**
#55 and #92.

`lastKeyMoved` sets which slider gets rendered last.

### CODE REVIEW

**Comment by jhblacklock** [comment]
@davidchin Any chance this can be added to the next release? We'd love to help if we can.

**Comment by davidchin** [comment]
Sure. Can you add a test case verifying that min/max can be the same? Also, can you add a prop so that your change is backward compatible?

**Comment by giorgim** [comment]
@davidchin We also have a requirement to set max and min value to same value. As I can tell it is planned that this feature is added to the component? (if yes, when?) thank you.

**Comment by jhblacklock** [comment]
@davidchin tests and prop added.  Thanks much!

**Comment by davidchin** [comment]
Thanks @jhblacklock, your changes have been released as `v1.3.0`

**Pull request merged**
