### PR TITLE
Add showLabel prop to show|hide label

### PR DESCRIPTION
**Pull request by gor181**
- Add showLabel prop, propType and declaration
- Fix other declarations.

### CODE REVIEW

**Comment by oyeanuj** [comment]
@gor181 Thanks for this! By any chance, do you have this same PR rebased on the latest refactor?

**Comment by gor181** [comment]
Hi @oyeanuj ,

Unfortunately not, it was a long time since I made this PR.
I think you can proceed with #68 and we can close this one?

Let me know what you think.
Goran

**Comment by oyeanuj** [comment]
That sounds good, thanks for responding!

**Comment by gor181** [comment]
Closed cheers.

**Pull request closed without merging**
